### ISSUE TITLE
Error running the triangle example

### ISSUE THREAD

**Issue by VarLad** [JuliaWGPU/WGPUCore.jl#15]
Hey! There seem to be some issues in the `examples/triangle.jl` file
```julia
ERROR: LoadError: MethodError: no method matching getCanvas(::Symbol)

Closest candidates are:
  getCanvas(::Val{:FallbackCanvas})
   @ WGPUCore ~/.julia/packages/WGPUCore/RwBiz/src/canvas.jl:57
  getCanvas()
   @ WGPUCore ~/.julia/packages/WGPUCore/RwBiz/src/canvas.jl:53

Stacktrace:
 [1] top-level scope
   @ /tmp/triangle.jl:36
in expression starting at /tmp/triangle.jl:36
```

**Comment by arhik** [comment]
platform  and other details of julia and WGPUCanvas versions you are using will help. Will look into as soon as I get those information.

**Comment by arhik** [comment]
@VarLad  Found the issue. You will have to include `WGPUCanvas` library for this to work.

**Comment by arhik** [comment]
@VarLad You can close this if its solved.

**Comment by VarLad** [comment]
Works now!
