### ISSUE TITLE
GetCocoaWindow not defined

### ISSUE THREAD

**Issue by pannous** [JuliaWGPU/WGPUCore.jl#8]
when calling `canvas = WGPUCore.defaultCanvas(WGPUCore.WGPUCanvas);` :

```ERROR: LoadError: UndefVarError: GetCocoaWindow not defined
Stacktrace:
 [1] getproperty
   @ ./Base.jl:31 [inlined]
 [2] defaultCanvas(::Type{WGPUCore.GLFWMacCanvas}; size::Tuple{Int64, Int64})
   @ WGPUCore ~/.julia/packages/WGPUCore/9zuGl/src/metalglfw.jl:82
 [3] defaultCanvas(::Type{WGPUCore.GLFWMacCanvas})
   @ WGPUCore ~/.julia/packages/WGPUCore/9zuGl/src/metalglfw.jl:74
 [4] top-level scope
   @ ~/dev/script/julia/triangle.jl:41
```

```
function defaultCanvas(::Type{GLFWMacCanvas}; size = (500, 500))
…    windowRef[] = window = GLFW.CreateWindow(size..., title)
    nswindow = GLFW.GetCocoaWindow(windowRef[]) |> Ref
       ^^^^
```

dependency GLFW v3.4.1

(on Mac M1)

**Comment by arhik** [comment]
Hello @pannous  I pushed a fix just 2 hours before you raised issue. Can you please update package in REPL and let me know. I didn't register the updated code yet, you might have to pull this repo directly in `pkg add `. Let me know

**Comment by arhik** [comment]
You can find code changes here -> c9e1243b0b2510ea7988d6cc09e1f6a9385a0182

**Comment by arhik** [comment]
registry is updated now.

**Comment by arhik** [comment]
Closing this after testing on M1 mac mini. Please feel free to re-raise it if you still have issue.
